mutation {
  createQuestionlists(
    input: [
      { id: "1", scope: "Actors", component: "Transparency", position: 1, question: "Who is involved in this project? e.g. researchers, organizations, end users", exampleanswer: "This project is a collaboration between IDS and MUMC+ - Maastricht University. The main involved researchers are J. Doe as Principal investigator of IDS and X.White as Principal Investigator of MUMC+. Heart failure patients from MUMC+ are involved via a clinical trial." },
        { id: "2", scope: "Objects", component: "Transparency", position: 2, question: "What the outputs or deliverables of the project are? e.g. types of data to collect/re-use, models or algorithms", exampleanswer: "In two phases the project creates Output1: Predictive models for heart failure Output2: A trial to externally evaluate the defined models." },
        { id: "3", scope: "Processes", component: "Transparency", position: 3, question: "What tools or processes make those outputs or deliverables (including data science lifecycle and project planning)? e.g. data collection, cleaning, data management", exampleanswer: "Phase 1: The data containing dr reports, labs and examinations  is extracted from the EHR of patients. The data is anonymized by removing all sensitive fields as well as names of patients.  The data then goes through a data science lifecycle of selecting, cleaning and transforming the input for the analysis. Several Machine learning models (Logistic regression, LSTM and SVM) are tested to select the best performing models. The process is re-iterated to optimise performance. Phase 2: Through randomised clinical trials, patients are selected to be involved in this study in addition to the standard care. A cohort of 100 patients is selected. At random they are assigned"  },
        { id: "4", scope: "Impacts", component: "Transparency", position: 4, question: "What outcomes and impacts the project will have in the world?  What are the intended aims of the project? What is the intended impact?", exampleanswer: "Better care for patients with heart failure risk Patient stratification for HF Identification of biomarkers for HF" },
        { id: "5", scope: "Actors", component: "Transparency", position: 5, question: "Have all the humans involved in the project been identified? This includes data scientists, downstream users of data science objects, & data subjects (e.g., patients).", exampleanswer: "The project team includes a RA (T. Ross) and a PhD student (M.Black). The downstream users will be the heart specialist doctors as well as the patients." },
        { id: "6", scope: "Actors", component: "Transparency", position: 6, question: "Are there formal agreements or explicitly described relationships between them? Examples of formal agreements: employment contracts (specifically length of contract, percentage of work, employee classifications, & other characteristics that might interact with ACCOUNTABILITY), consent forms, ethical approvals, intellectual property protocols, patents, non-disclosure agreements, contracts governing engagements", exampleanswer: "T. Ross has a postdoc contract for 3 years and will work 80% of time for the project. M. Black is a PhD student who has a 4-year contract. He will work 50% on the project.  Their responsibilities are described in the project plan. PIs (J. Doe and X.White) are responsible for managing and directing the work." },
        { id: "7", scope: "Actors", component: "Transparency", position: 7, question: "Are these formal agreements accessible by all of the actors?", exampleanswer: "The workpackage descriptions and responsibilities are shared with the project team." },
        { id: "8", scope: "Actors", component: "Transparency", position: 8, question: "Have the contributions of the humans who are involved been described?", exampleanswer: "Yes. The PhD will contribute to Phase 1 and will aid the execution of phase 1 of the project. The  research assistant will model and execute phase 2 of the project. Both principal investigators will supervise these phases." },
        { id: "9", scope: "Actors", component: "Transparency", position: 9, question: "Are there mechanisms in place to mitigate potential conflicts?", exampleanswer: "IPRs (Intellectual Property Rights) are regulated by Maastricht University." },
        { id: "10", scope: "Actors", component: "Transparency", position: 10, question: "Is there a provision for continuity and sustainability of the project and its resources over time? (e.g., do contact emails go to institutional email addresses, not individuals’?)", exampleanswer: "This question does not have an example answer yet." },
        { id: "11", scope: "Objects", component: "Transparency", position: 11, question: "Have all data/metadata/algorithms been described [this may be a link to a document]", exampleanswer: "This question does not have an example answer yet." },
        { id: "12", scope: "Objects", component: "Transparency", position: 12, question: "How will you make data and algorithms you used in the analysis transparent?", exampleanswer: "This question does not have an example answer yet." },
        { id: "13", scope: "Objects", component: "Transparency", position: 13, question: "How will you make data and algorithms that you used in the analysis accessible to others? (such as following the FAIR principles, meeting Open Science guidelines)", exampleanswer: "This question does not have an example answer yet." },
        { id: "14", scope: "Objects", component: "Transparency", position: 14, question: "Is any metadata given for the dataset?", exampleanswer: "Yes. The metadata contains the features and their corresponding descriptions: PatientID, Documents, Date, Department, Caregiver, Outcome" },
        { id: "15", scope: "Objects", component: "Transparency", position: 15, question: "Which algorithms/tools were used for analysis (if known)?", exampleanswer: "This question does not have an example answer yet." },
        { id: "16", scope: "Objects", component: "Transparency", position: 16, question: "Are your data and metadata in a repository? (provide links such as Github, Zenodo etc.)", exampleanswer: "This question does not have an example answer yet." },
        { id: "17", scope: "Objects", component: "Transparency", position: 17, question: "Are the data and metadata publicly available?", exampleanswer: "This question does not have an example answer yet." },
        { id: "18", scope: "Objects", component: "Transparency", position: 18, question: "What is the licence associated with the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "19", scope: "Objects", component: "Transparency", position: 19, question: "What is the quality of the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "20", scope: "Objects", component: "Transparency", position: 20, question: "What is the quantity of missing values in the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "21", scope: "Objects", component: "Transparency", position: 21, question: "Are there any terms and conditions specified on the use of the data/algorithm?", exampleanswer: "This question does not have an example answer yet." },
        { id: "22", scope: "Processes", component: "Transparency", position: 22, question: "How will you collect the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "23", scope: "Processes", component: "Transparency", position: 23, question: "How do you clean/preprocess the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "24", scope: "Processes", component: "Transparency", position: 24, question: "How do you analyze the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "25", scope: "Processes", component: "Transparency", position: 25, question: "Are all of the goals of the project accessible and understandable by all of the actors?", exampleanswer: "This question does not have an example answer yet." },
        { id: "26", scope: "Processes", component: "Transparency", position: 26, question: "How do you maintain/serve the project or your data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "27", scope: "Impacts", component: "Transparency", position: 27, question: "Within subcomponents of a process, are data FAIR?", exampleanswer: "This question does not have an example answer yet." },
        { id: "28", scope: "Impacts", component: "Transparency", position: 28, question: "Can you describe the implications of the project so that it is understandable by everyone?", exampleanswer: "This question does not have an example answer yet." },
        { id: "29", scope: "Impacts", component: "Transparency", position: 29, question: "Can you articulate how this project will affect people's life or research?", exampleanswer: "This question does not have an example answer yet." },
        { id: "30", scope: "Impacts", component: "Transparency", position: 30, question: "Have you described how this project might be misused?", exampleanswer: "This question does not have an example answer yet." },
        { id: "31", scope: "Impacts", component: "Transparency", position: 31, question: "Are there any terms and conditions specified on the use of data/algorithm?", exampleanswer: "This question does not have an example answer yet." },
        { id: "32", scope: "Actors", component: "Privacy", position: 32, question: "Is there an informed consent form signed by the human subjects in the project?", exampleanswer: "This question does not have an example answer yet." },
        { id: "33", scope: "Actors", component: "Privacy", position: 33, question: "Has a confidentiality agreement or non disclosure agreement been signed (if applicable)?", exampleanswer: "No NDA was required. A template for  NDA agreement can be found here." },
        { id: "34", scope: "Actors", component: "Privacy", position: 34, question: "Has a data usage agreement been signed by the researchers involved?", exampleanswer: "This question does not have an example answer yet." },
        { id: "35", scope: "Objects", component: "Privacy", position: 35, question: "Has a privacy protection method been used to make the data anonymous or pseudonymous?", exampleanswer: "In phase 1 the data were independently anonymised by the data collector. In phase the data was anonymised using random ids, and removing personal identifiable data fields." },
        { id: "36", scope: "Objects", component: "Privacy", position: 36, question: "Are you collecting identifiable personal information?", exampleanswer: "In phase 1 no.In phase 2, the data is initially recorded in EHR systems in which patients are fully identified. However, when the data is used for analysis the personal identifiable information is removed." },
        { id: "37", scope: "Objects", component: "Privacy", position: 37, question: "Are you collecting sensitive data (as defined by GDPR)", exampleanswer: "Yes, Data on the Physical condition of the participants" },
        { id: "38", scope: "Objects", component: "Privacy", position: 38, question: "Are the data you collected necessary to answer your research questions?", exampleanswer: "Yes, without the outputs of the project are not achievable." },
        { id: "39", scope: "Objects", component: "Privacy", position: 39, question: "Where/how do you process the data? (do you upload data to some servers to execute processing? Which tools do you use?)", exampleanswer: "The data is stored in Maastricht University Servers. For processing, the data might be downloaded to other machines but they remain within the Maastricht University Network. The data is deleted after the processing has finished and no further analysis is needed." },
        { id: "40", scope: "Objects", component: "Privacy", position: 40, question: "Where do you store data during and after your project?", exampleanswer: "During the project the data are securely stored at Maastricht University servers. After the project is over, the data are managed in cooperation with the Data Hub Maastricht University." },
        { id: "41", scope: "Objects", component: "Privacy", position: 41, question: "Is it secure?", exampleanswer: "yes" },
        { id: "42", scope: "Objects", component: "Privacy", position: 42, question: "Did you do your data management plan or use a template (such as https://dmponline.dcc.ac.uk/)?", exampleanswer: "Yes. Research Data Management Plan: https://www.zonmw.nl/en/research-and-results/fair-data-and-data-management/data-management-in-your-project/ " },
        { id: "43", scope: "Objects", component: "Privacy", position: 43, question: "Can third parties use the data? if so, how?", exampleanswer: "Not unless specific agreements are made. This is because of data privacy concerns." },
        { id: "44", scope: "Objects", component: "Privacy", position: 44, question: "Do your models and results reveal personal information directly?", exampleanswer: "No" },
        { id: "45", scope: "Objects", component: "Privacy", position: 45, question: "Can the outcome can be used to identify individuals indirectly?", exampleanswer: "This question does not have an example answer yet." },
        { id: "46", scope: "Objects", component: "Privacy", position: 46, question: "Is it possible that other people can combine your model/algorithm with other resources to identify individuals?", exampleanswer: "This question does not have an example answer yet." },
        { id: "47", scope: "Objects", component: "Privacy", position: 47, question: "Do participants have full control over their data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "48", scope: "Objects", component: "Privacy", position: 48, question: "Can they withdraw from the study at any point in time?", exampleanswer: "This question does not have an example answer yet." },
        { id: "49", scope: "Objects", component: "Privacy", position: 49, question: "Can they provide consent for secondary re-use of the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "50", scope: "Processes", component: "Privacy", position: 50, question: "Has a distributed learning method, such as the personal health train, been used where the algorithm is sent to the data provider and not the other way around?", exampleanswer: "This question does not have an example answer yet." },
        { id: "51", scope: "Processes", component: "Privacy", position: 51, question: "Has the analysis been conducted on the individual or on the group level?", exampleanswer: "This question does not have an example answer yet." },
        { id: "52", scope: "Processes", component: "Privacy", position: 52, question: "Has an information management system been set in place for auditing purposes?", exampleanswer: "This question does not have an example answer yet." },
        { id: "53", scope: "Impacts", component: "Privacy", position: 53, question: "Does your project help individuals protect their privacy and confidentiality?", exampleanswer: "This question does not have an example answer yet." },
        { id: "54", scope: "Impacts", component: "Privacy", position: 54, question: "Does your project increase society's confidence and trust in data science projects?", exampleanswer: "This question does not have an example answer yet." },
        { id: "55", scope: "Impacts", component: "Privacy", position: 55, question: "Will your outcome deliver a positive message to people about how their privacy and confidentiality have been handled?", exampleanswer: "This question does not have an example answer yet." },
        { id: "56", scope: "Actors", component: "Accountability", position: 56, question: "Has the researcher signed a code of conduct agreement?", exampleanswer: "Visara https://www.maastrichtuniversity.nl/about-um/organisation/codes-conduct-regulations Integrity code of conduct UM Processing of Personal Data https://www.maastrichtuniversity.nl/research/integrity-ethics/ethics-review" },
        { id: "57", scope: "Actors", component: "Accountability", position: 57, question: "Is it clear who is responsible for which part of the analysis outcome?", exampleanswer: "J. Doe is responsible for the analytical models and X.White is responsible for conducting the trial." },
        { id: "58", scope: "Actors", component: "Accountability", position: 58, question: "Does your organisation have protocols and procedures for dealing with an intentional or unintentional breakdown of transparency, privacy/confidentiality, or norm breaking?", exampleanswer: "UM  maintains a data processing of personal data in a registry. The project was registered by the principal investigators with the Data Protection Officer  via email (fg@maastrichtuniversity.nl)  In case of a data breach the project team needs to report via the ICTS Servicedesk under 'Report possible UM data leak'" },
        { id: "59", scope: "Actors", component: "Accountability", position: 59, question: "Are there protocols and procedures for dealing with conflicts between legal and ethical positions in projects?", exampleanswer: "https://www.maastrichtuniversity.nl/about-um/um-general-privacy-statement Whenever UM processes your personal data, it does so with a lawful basis for processing. A lawful basis for processing is the grounds for processing personal data. UM primarily processes your personal data to perform its public tasks in the field of the provision of academic education and research." },
        { id: "60", scope: "Actors", component: "Accountability", position: 60, question: "Does your organisation have a data protection officer? Data ethics review committees? Data stewards?", exampleanswer: "UM has a data protection officer. Raoul Winkens is the Data Protection Officer of Maastricht University. The person may be reached at: privacy@maastrichtuniversity.nl or fg@maastrichtuniversity.nl address" },
        { id: "61", scope: "Actors", component: "Accountability", position: 61, question: "Do employees have access to resources (e.g., training) for doing responsible data science?", exampleanswer: "The University Library offers courses on Research Data Management https://library.maastrichtuniversity.nl/research-support/rdm/services-tools-training/" },
        { id: "62", scope: "Actors", component: "Accountability", position: 62, question: "Do protections exist against lawsuit or damages for individual data scientists, users, or organisations?", exampleanswer: "This question does not have an example answer yet." },
        { id: "63", scope: "Objects", component: "Accountability", position: 63, question: "Has provenance been presented to track the origin of the data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "64", scope: "Objects", component: "Accountability", position: 64, question: "Do you know the original permissions attached to the data (in the case of re-use)?", exampleanswer: "This question does not have an example answer yet." },
        { id: "65", scope: "Objects", component: "Accountability", position: 65, question: "Are you following the original permissions that are attached to that data?", exampleanswer: "This question does not have an example answer yet." },
        { id: "66", scope: "Objects", component: "Accountability", position: 66, question: "Is there a description provided about potential biases, such as confounding factors?", exampleanswer: "This question does not have an example answer yet." },
        { id: "67", scope: "Objects", component: "Accountability", position: 67, question: "Is data quality an issue? If yes, what is the specific issue and how is it resolved?", exampleanswer: "This question does not have an example answer yet." },
        { id: "68", scope: "Objects", component: "Accountability", position: 68, question: "Is there a threshold for missing values? Is there a mechanism for reacting to missed thresholds?", exampleanswer: "This question does not have an example answer yet." },
        { id: "69", scope: "Processes", component: "Accountability", position: 69, question: "Is there a clear and transparent description of the process that is accessible?", exampleanswer: "This question does not have an example answer yet." },
        { id: "70", scope: "Processes", component: "Accountability", position: 70, question: "Who is responsible for which part of the analysis?", exampleanswer: "This question does not have an example answer yet." },
        { id: "71", scope: "Processes", component: "Accountability", position: 71, question: "Is there any control/checkpoints within the process?", exampleanswer: "This question does not have an example answer yet." },
        { id: "72", scope: "Impacts", component: "Accountability", position: 72, question: "What is the impact or the outcome of the analysis?", exampleanswer: "This question does not have an example answer yet." },
        { id: "73", scope: "Impacts", component: "Accountability", position: 73, question: "Is the outcome of your project understandable by others?", exampleanswer: "This question does not have an example answer yet." },
        { id: "74", scope: "Impacts", component: "Accountability", position: 74, question: "How are unintended outcomes communicated to the relevant organisation?", exampleanswer: "This question does not have an example answer yet." },
        { id: "75", scope: "Impacts", component: "Accountability", position: 75, question: "Are there protocols and procedures for dealing with conflicts between legal and ethical positions in projects?", exampleanswer: "This question does not have an example answer yet." },
        { id: "76", scope: "Impacts", component: "Accountability", position: 76, question: "Is there a procedure for dealing with unintended outcomes, either positive or negative?", exampleanswer: "This question does not have an example answer yet." },
        { id: "77", scope: "Impacts", component: "Accountability", position: 77, question: "How does your organisation deal with evaluations by external parties about the responsibility aspects of the project?", exampleanswer: "This question does not have an example answer yet." },
        { id: "78", scope: "Actors", component: "Societal values", position: 78, question: "What are the operative social values and norms that touch on who is involved in the project and how their roles are governed?", exampleanswer: "In which country is the work being conducted (Europe, US, Asia, etc)? Are there any code of conducts in place? Like this one: Netherlands Code of Conduct for Research Integrity https://www.universiteitenvannederland.nl/files/documents/Netherlands%20Code%20of%20Conduct%20for%20Research%20Integrity%202018.pdf Integrity and behaviour code for ICT staff at UM https://www.maastrichtuniversity.nl/file/7429/download?token=I_9r4Ek7" },
        { id: "79", scope: "Objects", component: "Societal values", position: 79, question: "What are the operative social values and norms that touch on data, algorithms, and other outputs or deliverables of the project?", exampleanswer: "Are there any laws or regulations in place to secure data protection (like the GDPR, CCPA in California), use of medical devices or other digital applications? For example the European Artificial Intelligence Act." },
        { id: "80", scope: "Processes", component: "Societal values", position: 80, question: "What are the operative social values and norms that touch on research processes and the data science lifecycle?", exampleanswer: "Are there any rules or standards for data collection? Did you pre-register your study somewhere (share your research data management plan)? For example via Center for Open Science (OSF)." },
        { id: "81", scope: "Impacts", component: "Societal values", position: 81, question: "What are the operative social values and norms that touch on the intended and unintended consequences and outcomes of your project?", exampleanswer: "Did you create a Data protection impact assessment (DPIA) which is obligatory under the GDPR in the Netherlands." },
        { id: "82", scope: "Impacts", component: "Societal values", position: 82, question: "Do the operative social values and norms conflict with each other?", exampleanswer: "No" },
        { id: "83", scope: "Impacts", component: "Societal values", position: 83, question: "Are all of the operative social values and norms in agreement with each other?", exampleanswer: "Yes" ,
    ]
  ) {
    questions {
    id
    question,
    component,
    scope,
    position
    }  
  }
}