version: '3.4'

services:

  neo4j:
    image: arm64v8/neo4j:4.4.11
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data/conf:/conf
      - ./neo4j-data/data:/data
      - ./neo4j-data/import:/import
      - ./neo4j-data/logs:/logs
      - ./neo4j-data/plugins:/plugins


  apollo:
    build:
      target: dev
    ports:
      - 4000:4000


  flutter:
    profiles:
      - donotbuild
    restart: "no"
    entrypoint: ["echo", "Flutter disabled for development!"]
