version: '3.4'

services:
  neo4j:
    image: neo4j:4.4.11
    restart: unless-stopped
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD-test}


  apollo:
    build: ./apollo
    restart: unless-stopped
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-test}
    links:
      - neo4j
    depends_on:
      - neo4j


  flutter:
    # build:
    #   context: ./mobile_client_new
    #   dockerfile: Dockerfile
    #   args:
    #     INSTALL_DEV: ${INSTALL_DEV-false}
    build: ./mobile_client_new
    restart: unless-stopped
    # environment:
    #   - GRAPHQL_URL=http://localhost:4000/graphql
    links:
      - apollo
    depends_on:
      - apollo
      - neo4j

