version: '4'

services:
  neo4j:
    image: neo4j:4.4.11
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins

    

    environment: 
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*

  apollo:
    build: ./apollo
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
    links:
      - neo4j
    depends_on:
      - neo4j
  
  flutter:
    build: ./mobile_client_new
    restart: unless-stopped
    environment:
      - GRAPHQL_URL=http://localhost:4000/graphql
    links:
      - apollo
    depends_on:
      - apollo
      - neo4j
    ports:
      - 80:80

